CREATE DATABASE IF NOT EXISTS Gestion_Pedidos;
USE Gestion_Pedidos;

CREATE TABLE Clientes (
    ID_CLIENTE INT PRIMARY KEY,
    NOM_CLIENTE VARCHAR(100),
    ESTADO VARCHAR(10)
);

CREATE TABLE Items (
    NUM_ITEM INT PRIMARY KEY,
    DESC_ITEM VARCHAR(100),
    PRECIO DECIMAL(10,2)
);

CREATE TABLE Ordenes (
    ID_ORDEN INT PRIMARY KEY,
    FECHA VARCHAR(20), 
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE)
);

CREATE TABLE Detalle_Orden (
    ID_ORDEN INT,
    NUM_ITEM INT,
    CANT INT,
    PRIMARY KEY (ID_ORDEN, NUM_ITEM),
    FOREIGN KEY (ID_ORDEN) REFERENCES Ordenes(ID_ORDEN),
    FOREIGN KEY (NUM_ITEM) REFERENCES Items(NUM_ITEM)
);

CREATE DATABASE IF NOT EXISTS Gestion_Peliculas_Alquiladas;
USE Gestion_Peliculas_Alquiladas;

CREATE TABLE Clientes (
    ID_CLIENTE INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    SALUTATION VARCHAR(10)
);

CREATE TABLE Direcciones (
    ID_PHYSICAL_ADDRESS VARCHAR(10) PRIMARY KEY,
    PHYSICAL_ADDRESS VARCHAR(200),
    ID_CLIENTE INT,
    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE)
);

CREATE TABLE Peliculas (
    ID_MOVIE VARCHAR(10) PRIMARY KEY,
    MOVIE_TITLE VARCHAR(150)
);

CREATE TABLE Renta_Peliculas (
    ID_RENTA INT AUTO_INCREMENT PRIMARY KEY, 
    ID_CLIENTE INT,
    ID_MOVIE VARCHAR(10),
    FOREIGN KEY (ID_CLIENTE) REFERENCES Clientes(ID_CLIENTE),
    FOREIGN KEY (ID_MOVIE) REFERENCES Peliculas(ID_MOVIE)
);


CREATE DATABASE IF NOT EXISTS Gestion_Tienda_Tecnologia;
USE Gestion_Tienda_Tecnologia;

CREATE TABLE Clientes (
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50)
);

CREATE TABLE Productos (
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(100)
);

CREATE TABLE Compras (
    CUSTOMER_ID INT,
    PRODUCT_ID INT,
    PRIMARY KEY (CUSTOMER_ID, PRODUCT_ID),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES Clientes(CUSTOMER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES Productos(PRODUCT_ID)
);


CREATE DATABASE IF NOT EXISTS Gestion_Biblioteca;
USE Gestion_Biblioteca;

CREATE TABLE Clientes (
    CLIENTE_ID VARCHAR(10) PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CUSTOMER_EMAIL VARCHAR(100),
    CUSTOMER_ADDRESS VARCHAR(200)
);

CREATE TABLE Libros (
    BOOK_ID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(150),
    BOOK_AUTHOR VARCHAR(100)
);

CREATE TABLE Ordenes (
    ORDER_ID INT PRIMARY KEY,
    CLIENTE_ID VARCHAR(10),
    ORDER_DATE DATE,
    FOREIGN KEY (CLIENTE_ID) REFERENCES Clientes(CLIENTE_ID)
);

CREATE TABLE Detalle_Orden (
    ORDER_ID INT,
    BOOK_ID INT,
    QUANTITY INT,
    PRECIO_VENTA DECIMAL(10,2),
    PRIMARY KEY (ORDER_ID, BOOK_ID),
    FOREIGN KEY (ORDER_ID) REFERENCES Ordenes(ORDER_ID),
    FOREIGN KEY (BOOK_ID) REFERENCES Libros(BOOK_ID)
);


CREATE DATABASE IF NOT EXISTS Gestion_Vivero;
USE Gestion_Vivero;

CREATE TABLE Ubicaciones (
    LOCATION_CODE INT PRIMARY KEY,
    LOCATION_NAME VARCHAR(100)
);

CREATE TABLE Categorias_Suelo (
    SOIL_CATEGORY CHAR(1) PRIMARY KEY,
    SOIL_DESCRIPTION VARCHAR(100)
);

CREATE TABLE Plantas (
    PLANT_CODE INT PRIMARY KEY,
    PLANT_NAME VARCHAR(100),
    SOIL_CATEGORY CHAR(1),
    FOREIGN KEY (SOIL_CATEGORY) REFERENCES Categorias_Suelo(SOIL_CATEGORY)
);

CREATE TABLE Plantas_Ubicacion (
    LOCATION_CODE INT,
    PLANT_CODE INT,
    PRIMARY KEY (LOCATION_CODE, PLANT_CODE),
    FOREIGN KEY (LOCATION_CODE) REFERENCES Ubicaciones(LOCATION_CODE),
    FOREIGN KEY (PLANT_CODE) REFERENCES Plantas(PLANT_CODE)
);